Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20191107.0.0"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3-pip python3-psycopg2 python-django
  SHELL

  config.vm.provision "file", source: "mycode", destination: "~/mycode"
end